# Generated by Django 4.0.4 on 2022-04-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_username_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
