# Generated by Django 4.0.4 on 2022-04-19 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_remove_company_id_job_job_id_company'),
        ('app', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_job',
            fields=[
                ('id_like_job', models.BigAutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
