# Generated by Django 4.0.4 on 2022-04-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pwd',
            field=models.CharField(default=1233, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
