# Generated by Django 4.0.4 on 2022-04-19 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
