# Generated by Django 4.0.4 on 2022-04-21 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_data_post_job_date_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_delete_document_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_work',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added', models.DateField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
