# Generated by Django 4.0.4 on 2022-04-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_job',
            fields=[
                ('id_type', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_job', models.FileField(upload_to='')),
                ('data_post', models.DateTimeField()),
                ('job_title', models.IntegerField()),
                ('detial', models.CharField(max_length=100)),
                ('property_job', models.CharField(max_length=50)),
                ('job_application', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.type_job')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_company', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('discripts', models.CharField(max_length=300)),
                ('welfare', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('id_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job')),
            ],
        ),
    ]
