# Generated by Django 4.0.4 on 2022-04-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_job_name_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
