# Generated by Django 4.0.4 on 2022-04-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id_job',
        ),
        migrations.AddField(
            model_name='job',
            name='id_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
