# Generated by Django 4.0.4 on 2022-04-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_id_job_job_id_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(default='None', upload_to='media/img/company'),
        ),
    ]
