# Generated by Django 4.0.4 on 2022-04-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='data_post',
            new_name='date_post',
        ),
    ]
