# Generated by Django 4.0.4 on 2022-05-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_data_post_job_date_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_application',
            fields=[
                ('Job_application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_application', to='company.job')),
            ],
        ),
    ]
