# Generated by Django 4.0.4 on 2022-05-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_job_application_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application',
            old_name='data',
            new_name='date',
        ),
    ]
